WebApplication1/WebApplication1/Areas/Admin/Controllers/ThemeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DataAccess.Repository.IRepository;
using WebApplication1.Models;
using WebApplication1.Utility;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ThemeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ThemeController(IUnitOfWork unitOfWork) 
        { 
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var themes = await _unitOfWork.Theme.GetAllAsync();
            return View(themes);
        }

        public async Task<IActionResult> Upsert(int? themeId)
        {
            Theme theme;
            if (themeId == null)
            {
                theme = new Theme();
            }
            else
            {
                theme = await _unitOfWork.Theme.GetAsync(u => u.Id == themeId);
            }

            return View(theme);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(Theme theme)
        {
            if (theme.Id == 0)
            {
                _unitOfWork.Theme.AddAsync(theme);
                TempData["success"] = $"The {theme.Name} has been added successfully!";
            }
            else
            {
                _unitOfWork.Theme.Update(theme);
                TempData["success"] = $"The {theme.Name} has been updated successfully!";
            }
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var themes = await _unitOfWork.Theme.GetAllAsync();
            return Json(new { data = themes });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var theme = await _unitOfWork.Theme.GetAsync(u => u.Id == id);
            if (theme == null || theme.Name == "Other")
            {
                return Json(new { success = false, message = "Deleting error!" });
            }

            var themeDefault = await _unitOfWork.Theme.GetAsync(u => u.Name == "Other");
            var collections = await _unitOfWork.Collection.GetAllAsync(u => u.ThemeId == id);
            foreach (var collection in collections)
            {
                collection.ThemeId = themeDefault.Id;
                _unitOfWork.Collection.Update(collection);
            }

            _unitOfWork.Theme.Remove(theme);
            _unitOfWork.Save();

            return Json(new { success = true, message = $"The {theme.Name} theme has been successfully deleted!" });
        }
    }
}

WebApplication1/WebApplication1/Areas/User/Controllers/CollectionController.cs
using AspNetCoreWebApp.CloudStorage;
using Duende.IdentityServer.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Buffers;
using System.Diagnostics;
using System.Drawing.Printing;
using System.Linq.Expressions;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using System.Text;
using WebApplication1.DataAccess.Repository.IRepository;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;
using WebApplication1.Utility;

namespace WebApplication1.Areas.User.Controllers
{
    [Area("User")]
    public class CollectionController : Controller
    {
        [BindProperty]
        public CollectionVM CollectionVm { get; set; }

        private readonly ILogger<CollectionController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICloudStorage _cloudStorage;
        public CollectionController(ILogger<CollectionController> logger,
            IUnitOfWork unitOfWork,
            ICloudStorage cloudStorage)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _cloudStorage = cloudStorage;
        }

        public async Task<IActionResult> Index(int collectionId)
        {
            var collection = await _unitOfWork.Collection
                .GetAsync(u => u.Id == collectionId, includeProperties: "Theme");

            var items = await _unitOfWork.Item.GetAllAsync(x => x.CollectionId == collectionId);
            foreach (var item in items)
            {
                var itemTags =
                    await _unitOfWork.ItemTag.GetAllAsync(u => u.ItemId == item.Id, includeProperties: "Tag");
                item.ItemTags = itemTags.ToList();
            }

            collection.Items = items;

            var themes = await _unitOfWork.Theme.GetAllAsync();

            CollectionVm = new CollectionVM
            {
                Collection = collection,
                ThemesList = themes.Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(CollectionVm);
        }

        [Authorize]
        public async Task<IActionResult> Upsert(int? collectionId)
        {
            Collection collection;
            if (collectionId == null)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                collection = new Collection
                {
                    ApplicationUserId = userId
                };
            }
            else
            {
                collection = await _unitOfWork.Collection.GetAsync(u => u.Id == collectionId);
                if (User.IsInRole(SD.Role_User))
                {
                    var claimsIdentity = (ClaimsIdentity)User.Identity;
                    var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                    if (collection.ApplicationUserId != userId)
                    {
                        return StatusCode(403);
                    }
                }
            }

            var themes = await _unitOfWork.Theme.GetAllAsync();

            CollectionVm = new CollectionVM
            {
                Collection = collection,
                ThemesList = themes.Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(CollectionVm);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Upsert()
        {
            var collection = CollectionVm.Collection;

            if (collection.ImageFile != null)
            {
                if (collection.ImageStorageName != null)
                {
                    await _cloudStorage.DeleteFileAsync(collection.ImageStorageName);
                }

                await UploadFile(collection);
            }

            if (collection.Id == 0)
            {
                _unitOfWork.Collection.Add(collection);
                TempData["success"] = "The collection has been successfully added!";
            }
            else
            {
                _unitOfWork.Collection.Update(collection);
                TempData["success"] = "The collection has been successfully updated!";
            }
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index), new { CollectionId = collection.Id });
        }

        [Authorize]
        [HttpDelete]
        public async Task<IActionResult> Delete(int collectionId)
        {
            var collection = await _unitOfWork.Collection.GetAsync(u => u.Id == collectionId);

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (collection.ApplicationUserId != userId && !User.IsInRole(SD.Role_Admin))
            {
                return StatusCode(403);
            }

            if (!string.IsNullOrEmpty(collection.ImageStorageName))
            {
                await _cloudStorage.DeleteFileAsync(collection.ImageStorageName);
            }

            _unitOfWork.Collection.Remove(collection);
            _unitOfWork.Save();

            return Json(new { success = true, message = "The collection has been successfully deleted!", collectionId = collectionId });
        }

        public async Task<IActionResult> List()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoadDataAsync()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            Expression<Func<Collection, bool>> filter = u => true;
            if (User.IsAuthenticated() && User.IsInRole(SD.Role_User))
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                filter = u => u.ApplicationUserId == userId;
            }

            var collections = await _unitOfWork.Collection
                .GetAllAsync(filter,
                    searchText: searchValue,
                    skipAmount: skip, pageSize: pageSize,
                    ordering: $"{sortColumn} {sortColumnDirection}",
                    includeProperties: "Theme");

            var recordsTotal = collections.Count();

            return Json(new { Draw = draw, RecordsFiltered = recordsTotal, RecordsTotal = recordsTotal, Data = collections });
        }

        public async Task<IActionResult> ExportToCsv(int collectionId)
        {
            var collection = await _unitOfWork.Collection
                .GetAsync(u => u.Id == collectionId, includeProperties: "Theme");

            var items = await _unitOfWork.Item.GetAllAsync(x => x.CollectionId == collectionId);
            foreach (var item in items)
            {
                var itemTags =
                    await _unitOfWork.ItemTag.GetAllAsync(u => u.ItemId == item.Id, includeProperties: "Tag");
                item.ItemTags = itemTags.ToList();
            }

            collection.Items = items;

            var builder = new StringBuilder();
            builder.AppendLine("Id,Name,Description,Theme");
            builder.AppendLine($"{collection.Id},{collection.Name},{collection.Description},{collection.Theme.Name}\n");

            if (collection.Items.Count() > 0)
            {
                builder.AppendLine("Id,Name,Tags");
            }
            foreach (var item in collection.Items)
            {
                var tags = string.Join(", ", item.ItemTags.Select(u => u.Tag.Name));
                builder.AppendLine($"{item.Id},{item.Name},{tags}");
            }

            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "Collection.csv");
        }

        public async Task<IActionResult> ExportCollectionsToCsv()
        {
            Expression<Func<Collection, bool>> filter = u => true;
            if (User.IsAuthenticated() && User.IsInRole(SD.Role_User))
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                filter = u => u.ApplicationUserId == userId;
            }

            var collections = await _unitOfWork.Collection.GetAllAsync(filter, includeProperties: "Theme");
            foreach (var collection in collections)
            {
                var items = await _unitOfWork.Item.GetAllAsync(x => x.CollectionId == collection.Id);
                foreach (var item in items)
                {
                    var itemTags =
                        await _unitOfWork.ItemTag.GetAllAsync(u => u.ItemId == item.Id, includeProperties: "Tag");
                    item.ItemTags = itemTags.ToList();
                }

                collection.Items = items;
            }

            var builder = new StringBuilder();
            foreach (var collection in collections)
            {
                builder.AppendLine("Id,Name,Description,Theme");

WebApplication1/WebApplication1/Areas/User/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DataAccess.Repository.IRepository;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Areas.User.Controllers
{
    [Area("User")]
    public class SearchController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public SearchController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index(string searchText)
        {
            var items = (await _unitOfWork.Item.GetAllAsync(searchText: searchText)).ToList();
            foreach (var item in items)
            {
                var itemTagsForItem = await _unitOfWork.ItemTag.GetAllAsync(i => i.ItemId == item.Id, includeProperties: "Tag");
                item.ItemTags = itemTagsForItem.ToList();
            }
            var itemTags = await _unitOfWork.ItemTag.GetAllAsync(u => u.Tag.Name.Contains(searchText), includeProperties: "Tag");
            foreach (var itemTag in itemTags)
            {
                if (!items.Any(u => u.Id == itemTag.ItemId))
                {
                    var item = await _unitOfWork.Item.GetAsync(u => u.Id == itemTag.ItemId);
                    item.ItemTags = (await _unitOfWork.ItemTag.GetAllAsync(u => u.ItemId == item.Id, includeProperties: "Tag")).ToList();
                    items.Add(item);
                }
            }

            var collections = (await _unitOfWork.Collection.GetAllAsync(searchText: searchText, includeProperties: "Theme")).ToList();

            var searchVm = new SearchVM
            {
                Items = items,
                Collections = collections,
                SearchText = searchText,
            };

            return View(searchVm);
        }

        public async Task<IActionResult> SearchByTag(int tagId)
        {
            var itemTags = await _unitOfWork.ItemTag.GetAllAsync(u => u.TagId == tagId, includeProperties: "Item");
            var items = itemTags.Select(u => u.Item);
            foreach (var item in items)
            {
                var itemTagsForItem = await _unitOfWork.ItemTag.GetAllAsync(u => u.ItemId == item.Id, includeProperties: "Tag");
                item.ItemTags = itemTagsForItem.ToList();
            }

            var tag = await _unitOfWork.Tag.GetAsync(u => u.Id == tagId);
            var searchVm = new SearchVM
            {
                Items = items,
                Collections = new List<Collection>(),
                SearchText = tag.Name
            };

            return View("Index", searchVm);
        }
    }
}

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="User" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <div class="d-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-between">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Collection" asp-action="List">Collections</a>
                        </li>
                    </ul>
                </div>
                <form id="formSearch" class="input-group mx-2" asp-area="" asp-controller="Search" asp-action="Index">
                    <div class="input-group">
                        <input id="searchBar" type="search" class="form-control py-3" placeholder="Enter search text" name="searchText">
                        <button class="btn btn-secondary py-3" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
                @if (User.IsInRole(SD.Role_Admin))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Theme" asp-action="Index">
                                        Theme
                                    </a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">
                                        Manage Users
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                }
                <div class="p-2 border rounded">
                    <div class="form-check form-switch" id="btnSwitch">
                        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault"/>
                        <label class="form-check-label" for="flexSwitchCheckDefault">Mode</label>
                    </div>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="User" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>
        const currentTheme = localStorage.getItem('theme') || 'dark';
        document.documentElement.setAttribute('data-bs-theme', currentTheme);

        document.getElementById('btnSwitch').addEventListener('click', () => {
            if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
                document.documentElement.setAttribute('data-bs-theme', 'light');
                localStorage.setItem('theme', 'light');
            }
            else {
                document.documentElement.setAttribute('data-bs-theme', 'dark');
                localStorage.setItem('theme', 'dark');
            }
        });

    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/j0pn28epnjcxi8jl20fdyker8fytbviumi0a8oymkxe4idsj/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/WebApplication1/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}