WebApplication1/WebApplication1/Areas/Admin/Controllers/ThemeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DataAccess.Repository.IRepository;
using WebApplication1.Models;
using WebApplication1.Utility;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ThemeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ThemeController(IUnitOfWork unitOfWork) 
        { 
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var themes = await _unitOfWork.Theme.GetAllAsync();
            return View(themes);
        }

        public async Task<IActionResult> Upsert(int? themeId)
        {
            Theme theme;
            if (themeId == null)
            {
                theme = new Theme();
            }
            else
            {
                theme = await _unitOfWork.Theme.GetAsync(u => u.Id == themeId);
            }

            return View(theme);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(Theme theme)
        {
            if (theme.Id == 0)
            {
                _unitOfWork.Theme.AddAsync(theme);
                TempData["success"] = $"The {theme.Name} has been added successfully!";
            }
            else
            {
                _unitOfWork.Theme.Update(theme);
                TempData["success"] = $"The {theme.Name} has been updated successfully!";
            }
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var themes = await _unitOfWork.Theme.GetAllAsync();
            return Json(new { data = themes });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var theme = await _unitOfWork.Theme.GetAsync(u => u.Id == id);
            if (theme == null || theme.Name == "Other")
            {
                return Json(new { success = false, message = "Deleting error!" });
            }

            var themeDefault = await _unitOfWork.Theme.GetAsync(u => u.Name == "Other");
            var collections = await _unitOfWork.Collection.GetAllAsync(u => u.ThemeId == id);
            foreach (var collection in collections)
            {
                collection.ThemeId = themeDefault.Id;
                _unitOfWork.Collection.Update(collection);
            }

            _unitOfWork.Theme.Remove(theme);
            _unitOfWork.Save();

            return Json(new { success = true, message = $"The {theme.Name} theme has been successfully deleted!" });
        }
    }
}

WebApplication1/WebApplication1/Areas/Admin/Views/Theme/Index.cshtml
@model IEnumerable<Theme>

<div class="text-center">
    <h2 class="mb-4">Theme List</h2>
    <div class="text-end mb-2">
        <a asp-action="Upsert" class="btn btn-primary" style="width:150px">
            <i class="bi bi-plus-circle"></i> Add Item
        </a>
    </div>
    <table id="tblThemes" class="table table-bordered table-striped table-hover" style="width:100%">
        <thead>
            <tr>
                <th>№</th>
                <th>Name</th>
                <th style="width: 20%"></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts {
    <script>
        var dataTable;

        $(document).ready(function () {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tblThemes').DataTable({
                "ajax": { url: '/admin/theme/getall' },
                "columns": [
                    { data: 'id', "width": "20%" },
                    { data: 'name', "width": "60%" },
                    {
                        data: 'id',
                        "render": function (data)
                        {
                            if (data != 1) {
                                return `<div class="text-inline">
                                        <a href="/admin/theme/upsert?themeId=${data}" class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit </a>
                                        <a onClick="Delete('/admin/theme/delete/${data}')" class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete </a>
                                    </div>`
                            }
                            return ``;
                        },
                        "width": "20%"
                    }
                ]
            });
        }

        function Delete(url) {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        success: function (data) {
                            dataTable.ajax.reload();
                            toastr.success(data.message);
                        }
                    })
                }
            });
        }
    </script>
}

WebApplication1/WebApplication1/Areas/Admin/Views/Theme/Upsert.cshtml
@model Theme

<form method="post" class="row">
    <input asp-for="Id" hidden />
    <div class="col-10 offset-1 p-3">
        <div class="col-12 col-lg-6 form-outline mb-3">
            <label asp-for="Name" class="ms-2 text-muted"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="row pt-2">
            <div class="col-6 col-md-3">
                @if (Model.Id == 0)
                {
                    <button type="submit" class="btn btn-primary form-control">
                        Create
                    </button>
                }
                else
                {
                    <button type="submit" class="btn btn-primary form-control">
                        Save
                    </button>
                }
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Theme" asp-action="Index" class="btn btn-outline-primary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}